# -*- coding: utf-8 -*-
"""ad day 40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srFpQIOqQz3SEG7UWOD8RW5HboSWykVY
"""

!pip install streamlit

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix

data=pd.read_csv(r"/content/Heart_Disease_Dataset.csv")

data.tail()

data.shape

data.info()

data.describe()

data[data.duplicated]

len(data[data.duplicated()])

##
for column in data.columns:
  print(data[column].value_counts())

