# -*- coding: utf-8 -*-
"""ad day 44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14z9hVe3OJ1Avt0ZTq8wgEIKf4LRIGmK0
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

data={"color":["red","blue","green","yellow",]}
df=pd.DataFrame(data)
df.head()

label_encoder=LabelEncoder()
df['color']=label_encoder.fit_transform(df["color"])
df.head()

one_hot_encoding=OneHotEncoder(sparse_output=False, handle_unknown='ignore')
color_encoded=one_hot_encoding.fit_transform(df[["color"]])
color_encoded_df=pd.DataFrame(color_encoded,columns=one_hot_encoding.get_feature_names_out(["color"]))
df=pd.concat([df,color_encoded_df],axis=1)
df.head()

