# -*- coding: utf-8 -*-
"""ad day 48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsH1vRRklwHq0T5CpPm_ohgzpMRhz2Y_
"""

from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

file_name='/content/pima-indians-diabetes.data.csv'
names=['preg','plas','skin','test','mass','pedi','age','class']
dataframe=read_csv(file_name,names=names)
dataframe.head()

list[1,2,4,5,6,12]

array=dataframe.values
X=array[:,0:6]
Y=array[:,6]

